# Generated by Django 4.2.13 on 2024-08-12 14:12

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_alter_photo_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(upload_to=website.models.upload_original_image),
        ),
    ]
